name: Deploy to shinyapps.io

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:

  deploy-app-to-shinyapps:

    runs-on: ubuntu-latest

    steps:
    
      - name: Install R packages
        run: |
          # Install required R packages
          R -e "install.packages(c('tidyverse', 'shiny','dplyr',
          'factoextra', 'cluster','NbClust','ClusterR', 'mclust','fpc',
          'modeest', 'fastDummies','ramify','scales', 'shinyjs','vcd','rsconnect'))"

      - name: Deploy app to shinyapps.io
        run: |
          cd ${{ github.workspace }}/ClusterTest
          R -e "library(rsconnect); rsconnect::deployApp('.', appName = 'YMLTest')"
