name: Deploy to shinyapps.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: macOS-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3'
        
    - name: Install rsconnect
      run: |
        R -e 'install.packages("rsconnect")'
        
    - name: Install required packages
      run: |
        R -e 'install.packages(c("tidyverse", "shiny", "dplyr", "factoextra", "cluster", "NbClust", "ClusterR", "mclust", "fpc", "modeest", "fastDummies", "ramify", "scales", "shinyjs", "vcd"))'

    - name: Deploy app to shinyapps.io
      env:
        SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_NAME }}
        SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
        SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
      run: |
         cd ${{ github.workspace }}/ClusteringPrototype
         Rscript \
           -e 'library(rsconnect)' \
           -e 'rsconnect::setAccountInfo(name=Sys.getenv("SHINYAPPS_ACCOUNT"),token=Sys.getenv("SHINYAPPS_TOKEN"), secret=Sys.getenv("SHINYAPPS_SECRET"))' \
           -e 'rsconnect::deployApp(".",appName="clustering")'
